# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
DISABLE_LINTERS:
  - JAVASCRIPT_STANDARD
  - TYPESCRIPT_STANDARD
FILEIO_REPORTER: false
PRE_COMMANDS:
  - continue_if_failed: false
    command: yarn install --frozen-lockfile
    cwd: workspace
SHOW_ELAPSED_TIME: true
